apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myakspvc3
  namespace: arbaz
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: myaks