apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: arbazm10/vprofiledb:latest
          #args:
          #- "--ignore-db-dir"
          #- "lost+found"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: volume
        ports:
        - name: vprodb-port
          containerPort: 3306
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "200m"
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: db-pass
      nodeSelector:
        zone: centralus
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: myakspvc2


